import { useState } from "react";
import { Bell, Check, CircleHelp, CreditCard, KeyRound, Link2, Moon, Paintbrush, Save, Sun, UserRound, UsersRound, type LucideIcon } from "lucide-react";
import { Avatar, Badge, Button, Field, Input, Panel, Select } from "../components/ui";
import { useAppStore } from "../store/useAppStore";

type SettingsTab = "Profile" | "Workspace" | "Notifications" | "Billing" | "Appearance" | "Security" | "Integrations";
const tabs: { name: SettingsTab; icon: LucideIcon }[] = [
  { name: "Profile", icon: UserRound }, { name: "Workspace", icon: UsersRound }, { name: "Notifications", icon: Bell }, { name: "Billing", icon: CreditCard }, { name: "Appearance", icon: Paintbrush }, { name: "Security", icon: KeyRound }, { name: "Integrations", icon: Link2 },
];

export default function SettingsPage() {
  const { theme, toggleTheme, addToast } = useAppStore();
  const [tab, setTab] = useState<SettingsTab>("Profile");
  const [profile, setProfile] = useState({ name: "Alex Carter", email: "alex@freelanceos.com", role: "Independent designer", timezone: "America/Los_Angeles" });
  const [workspace, setWorkspace] = useState({ name: "Alex's Workspace", category: "Design & creative", currency: "USD ($)" });
  const [toggles, setToggles] = useState({ invoice: true, project: true, digest: false, product: false });

  const save = () => addToast(`${tab} settings saved successfully.`);
  const toggle = (key: keyof typeof toggles) => setToggles((current) => ({ ...current, [key]: !current[key] }));

  return (
    <div>
      <div className="settings-header"><div><div className="eyebrow">MAKE IT YOURS</div><h1>Settings</h1><p>Set up a workspace that works the way you do.</p></div><Button onClick={save}><Save size={14} />Save changes</Button></div>
      <div className="settings-layout"><aside className="settings-nav">{tabs.map(({ name, icon: Icon }) => <button key={name} className={tab === name ? "settings-nav-active" : ""} onClick={() => setTab(name)}><Icon size={15} />{name}</button>)}<div className="settings-help"><CircleHelp size={15} /><strong>Need a hand?</strong><span>Our help center has answers to common questions.</span><button onClick={() => addToast("Help center is coming soon.", "info")}>Visit help center<Check size={12} /></button></div></aside><div className="settings-content">
        {tab === "Profile" && <><SettingsSection title="Profile information" description="The basics your clients and collaborators see." action={<Badge tone="green">Personal profile</Badge>}><div className="profile-settings-card"><Avatar name={profile.name} color="profile" size="lg" /><div><strong>Profile photo</strong><span>JPG or PNG. Maximum 2MB.</span></div><Button size="sm" onClick={() => addToast("Photo upload dialog opened.", "info")}>Upload photo</Button></div><div className="settings-form-grid"><Field label="Full name"><Input value={profile.name} onChange={(event) => setProfile({ ...profile, name: event.target.value })} /></Field><Field label="Email address"><Input type="email" value={profile.email} onChange={(event) => setProfile({ ...profile, email: event.target.value })} /></Field><Field label="What do you do?"><Input value={profile.role} onChange={(event) => setProfile({ ...profile, role: event.target.value })} /></Field><Field label="Time zone"><Select value={profile.timezone} onChange={(event) => setProfile({ ...profile, timezone: event.target.value })}><option value="America/Los_Angeles">Pacific Time (UTC-08:00)</option><option value="America/New_York">Eastern Time (UTC-05:00)</option><option value="Europe/London">London (UTC+00:00)</option><option value="Europe/Paris">Central European Time (UTC+01:00)</option></Select></Field></div></SettingsSection><SettingsSection title="Profile visibility" description="Choose what appears on your public client-facing profile."><SettingToggle title="Show your availability" detail="Let new clients know when you have room for work." active={true} onChange={() => addToast("Availability setting updated.", "info")} /><SettingToggle title="Show your freelance category" detail="Help clients understand the kind of work you do." active={true} onChange={() => addToast("Profile visibility updated.", "info")} /></SettingsSection></>}
        {tab === "Workspace" && <><SettingsSection title="Workspace details" description="A few details about the business you are building."><div className="settings-form-grid"><Field label="Workspace name"><Input value={workspace.name} onChange={(event) => setWorkspace({ ...workspace, name: event.target.value })} /></Field><Field label="Freelance category"><Select value={workspace.category} onChange={(event) => setWorkspace({ ...workspace, category: event.target.value })}><option>Design & creative</option><option>Development & engineering</option><option>Writing & content</option><option>Marketing & growth</option><option>Consulting & strategy</option><option>Other</option></Select></Field><Field label="Default currency"><Select value={workspace.currency} onChange={(event) => setWorkspace({ ...workspace, currency: event.target.value })}><option>USD ($)</option><option>EUR (€)</option><option>GBP (£)</option><option>CAD ($)</option><option>AUD ($)</option></Select></Field><Field label="Week starts on"><Select defaultValue="Monday"><option>Monday</option><option>Sunday</option></Select></Field></div></SettingsSection><SettingsSection title="Workspace members" description="Your work, your way. Bring collaborators in when you need them."><div className="workspace-member-row"><Avatar name="Alex Carter" color="profile" /><div><strong>Alex Carter</strong><span>alex@freelanceos.com</span></div><Badge tone="neutral">Owner</Badge><button onClick={() => addToast("You are the workspace owner.", "info")}>Manage</button></div><Button onClick={() => addToast("Invite link copied to clipboard.", "info")}><UsersRound size={14} />Invite a collaborator</Button></SettingsSection></>}
        {tab === "Notifications" && <SettingsSection title="Email notifications" description="Choose which moments make it into your inbox."><SettingToggle title="Invoice and payment activity" detail="Payment received, upcoming due dates, and overdue invoices." active={toggles.invoice} onChange={() => toggle("invoice")} /><SettingToggle title="Project updates" detail="Client comments, status changes, and key deadlines." active={toggles.project} onChange={() => toggle("project")} /><SettingToggle title="Weekly business digest" detail="A calm Monday summary of your business and priorities." active={toggles.digest} onChange={() => toggle("digest")} /><SettingToggle title="Product news and tips" detail="Occasional notes about new features and freelance workflows." active={toggles.product} onChange={() => toggle("product")} /></SettingsSection>}
        {tab === "Billing" && <><SettingsSection title="Your plan" description="Everything you need to run your independent business."><div className="billing-plan-card"><div className="billing-plan-mark"><Paintbrush size={17} /></div><div><span>CURRENT PLAN</span><strong>Freelancer · Early access</strong><small>You're on the founding member plan.</small></div><Badge tone="green">Active</Badge></div><div className="billing-usage-list"><UsageRow title="Active projects" value="5 of unlimited" progress={35} /><UsageRow title="Clients" value="6 of unlimited" progress={25} /><UsageRow title="AI generations" value="24 of 100 this month" progress={24} /></div><Button variant="primary" onClick={() => addToast("Billing plans will be available soon.", "info")}>Explore plans<CreditCard size={14} /></Button></SettingsSection><SettingsSection title="Payment method" description="Add a payment method for future invoices and workspace billing."><div className="empty-payment-method"><CreditCard size={19} /><div><strong>No payment method added</strong><span>Your payment details are securely stored by our payment partner.</span></div><Button size="sm" onClick={() => addToast("Secure payment setup is coming soon.", "info")}>Add payment method</Button></div></SettingsSection></>}
        {tab === "Appearance" && <><SettingsSection title="Theme" description="A comfortable workspace for the time of day you work best."><div className="theme-choice-grid"><button className={`theme-choice ${theme === "light" ? "theme-choice-active" : ""}`} onClick={() => theme !== "light" && toggleTheme()}><span className="theme-preview theme-preview-light"><span /><span /><span /></span><div><Sun size={15} /><strong>Light</strong></div><small>Warm and bright</small></button><button className={`theme-choice ${theme === "dark" ? "theme-choice-active" : ""}`} onClick={() => theme !== "dark" && toggleTheme()}><span className="theme-preview theme-preview-dark"><span /><span /><span /></span><div><Moon size={15} /><strong>Dark</strong></div><small>Easy on the eyes</small></button><button className="theme-choice" onClick={() => addToast("System theme preference saved.", "info")}><span className="theme-preview theme-preview-system"><span /><span /><span /></span><div><Paintbrush size={15} /><strong>System</strong></div><small>Match your device</small></button></div></SettingsSection><SettingsSection title="Workspace density" description="Tune the rhythm of your workspace."><div className="density-options"><label><input type="radio" name="density" defaultChecked />Comfortable<span>A little room to breathe</span></label><label><input type="radio" name="density" />Compact<span>More information at a glance</span></label></div></SettingsSection></>}
        {tab === "Security" && <><SettingsSection title="Sign-in security" description="A few ways to protect the work behind your business."><SettingToggle title="Two-factor authentication" detail="Add a second step to protect your account." active={false} onChange={() => addToast("Two-factor authentication setup opened.", "info")} /><div className="security-row"><div><strong>Password</strong><span>Last changed more than 90 days ago</span></div><Button onClick={() => addToast("Password update form opened.", "info")}>Update password</Button></div><div className="security-row"><div><strong>Active sessions</strong><span>You're signed in on this device.</span></div><Badge tone="green">1 active session</Badge></div></SettingsSection><SettingsSection title="Data & privacy" description="You are in control of your workspace information."><Button onClick={() => addToast("Your data export is being prepared.", "info")}>Download my data</Button><button className="danger-link" onClick={() => addToast("Contact support to close your workspace.", "info")}>Close my workspace</button></SettingsSection></>}
        {tab === "Integrations" && <SettingsSection title="Connected tools" description="Bring your favorite tools into your workspace."><IntegrationRow icon="G" name="Google Calendar" detail="Keep client meetings and project dates in sync." connected={false} onClick={() => addToast("Google Calendar connection is coming soon.", "info")} /><IntegrationRow icon="S" name="Stripe" detail="Get paid online and automatically track invoice status." connected={false} onClick={() => addToast("Stripe connection is coming soon.", "info")} /><IntegrationRow icon="F" name="Figma" detail="Bring your design files closer to your project work." connected={false} onClick={() => addToast("Figma connection is coming soon.", "info")} /><IntegrationRow icon="O" name="OpenAI-compatible API" detail="Connect your preferred model endpoint for AI workflows." connected={false} onClick={() => addToast("AI provider settings opened.", "info")} /></SettingsSection>}
      </div></div>
    </div>
  );
}

function SettingsSection({ title, description, action, children }: { title: string; description: string; action?: React.ReactNode; children: React.ReactNode }) {
  return <Panel className="settings-section"><div className="settings-section-heading"><div><h2>{title}</h2><p>{description}</p></div>{action}</div><div className="settings-section-content">{children}</div></Panel>;
}

function SettingToggle({ title, detail, active, onChange }: { title: string; detail: string; active: boolean; onChange: () => void }) {
  return <div className="setting-toggle-row"><div><strong>{title}</strong><span>{detail}</span></div><button className={`toggle-switch ${active ? "toggle-on" : ""}`} onClick={onChange} aria-pressed={active} aria-label={`${active ? "Disable" : "Enable"} ${title}`}><i /></button></div>;
}

function UsageRow({ title, value, progress }: { title: string; value: string; progress: number }) {
  return <div className="usage-row"><div><strong>{title}</strong><span>{value}</span></div><div className="usage-track"><span style={{ width: `${progress}%` }} /></div></div>;
}

function IntegrationRow({ icon, name, detail, connected, onClick }: { icon: string; name: string; detail: string; connected: boolean; onClick: () => void }) {
  return <div className="integration-row"><span className="integration-icon">{icon}</span><div><strong>{name}</strong><small>{detail}</small></div>{connected ? <Badge tone="green">Connected</Badge> : <Button size="sm" onClick={onClick}>Connect</Button>}</div>;
}